### ISSUE TITLE
Preprocessing data

### ISSUE THREAD

**Issue by rmoretti9** [qismib/QuaKe#3]
Hi

The geant4 track contained in the root files are distributed along the large volume of the simulation (about 50x50x50 cm^3 for 1cm-long track). To convert the tracks into downsampled 3D histograms, we shift them all towards the centre, in such a way that the start of the track coincides with the origin, and then we build a smaller 4x4x4 cm^3 histograms to embed them.

I think that this operation, while doable for simulated data, cannot be generalized to real experimental data, when only histograms are provided without the high resolution tracks. In fact, we are implying that every track begins in the same position with respect to the grid (in the example below, at the intersection of 4 bins in (0,0)):

![noshift](https://user-images.githubusercontent.com/70576698/156774486-3cb00381-fe10-45d3-9dae-a2f56fc4b67d.png)

While in general the track could originate everywhere inside the bin. This changes a lot the resulting output, because the bins are about as big as the track itself.
![shift](https://user-images.githubusercontent.com/70576698/156774514-af32ce1b-e715-4010-87d7-6656f1dc82f1.png)

So for every track I added a random uniform shift in the range [-binsize, +binsize] in all directions. I don't know if this affects the classification performance, but I believe that this may represent a more realistic dataset.

Do you think this is correct?

Another approach could be building the histogram around the mean point of the tracks, but this gives some (solvable) issues related to far energy deposits, such as truncating the track.

**Comment by dguff** [comment]
Ciao Roberto, 
  I think your approach is absolutely reasonable. I can't see any worrisome drawback at the moment.

**Comment by rmoretti9** [comment]
> Ciao Roberto, I think your approach is absolutely reasonable. I can't see any worrisome drawback at the moment.
Thank you Daniele
